import { createThemeContract } from "@vanilla-extract/css";

export const aliasContract = createThemeContract({
    primary: {
      softest: null,
      softer: null,
      soft: null,
      lightest: null,
      light: null,
      default: null,
      dark: null,
      darker: null,
      darkest: null,
    },
    secondary: {
      softest: null,
      softer: null,
      soft: null,
      lightest: null,
      light: null,
      default: null,
      dark: null,
      darker: null,
      darkest: null,
    },
    tertiary: {
      default: null,
      softest: null,
    },
    quaternary: {
      default: null,
      softest: null,
    },
    quinary: null,
    blackAlternative: null,
    slate: null,
    white: null,
    grey: {
      softest: null,
      softer: null,
      soft: null,
      lightest: null,
      light: null,
      default: null,
      dark: null,
      darker: null,
      darkest: null,
    },
    success: {
      softest: null,
      default: null,
      dark: null,
      darkest: null,
    },
    critical: {
      softest: null,
      default: null,
      dark: null,
      darkest: null,
    },
    warning: {
      softest: null,
      default: null,
      dark: null,
      darkest: null,
    },
    information: {
      softest: null,
      default: null,
      dark: null,
      darkest: null,
    },
    attention: {
      softest: null,
      default: null,
      dark: null,
      darkest: null,
    },
});