name: "Test"
on:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Install Deps"
        run: npm ci

      #   - name: "Generate Coverage Report"
      #     run: npx vitest run --coverage.enabled --coverage.reporter=json-summary --config ./packages/ui/vite.config.ts

      - name: "Test"
        run: npm run test:coverage

      - name: "Report Coverage"
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: "Design System"
          vite-config-path: ./packages/ui/vite.config.ts
          json-final-path: ./packages/ui/coverage/coverage-final.json
          json-summary-path: ./packages/ui/coverage/coverage-summary.json
